<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%@ page import="jb.model.TfmGoods" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<script type="text/javascript">
	$(function() {
		parent.$.messager.progress('close');		
	});
</script>
<div class="easyui-layout" data-options="fit:true,border:false">
	<div data-options="region:'center',border:false">
		<table class="table table-hover table-condensed">
				<tr>	
					<th><%=TfmGoods.ALIAS_ADDTIME%></th>	
					<td>
						${fmGoods.addtime}							
					</td>							
					<th><%=TfmGoods.ALIAS_UPDATETIME%></th>	
					<td>
						${fmGoods.updatetime}							
					</td>							
				</tr>		
				<tr>	
					<th><%=TfmGoods.ALIAS_ISDELETED%></th>	
					<td>
						${fmGoods.isdeleted}							
					</td>							
					<th><%=TfmGoods.ALIAS_NAME%></th>	
					<td>
						${fmGoods.name}							
					</td>							
				</tr>		
				<tr>	
					<th><%=TfmGoods.ALIAS_PRICE%></th>	
					<td>
						${fmGoods.price}							
					</td>							
					<th><%=TfmGoods.ALIAS_UNIT%></th>	
					<td>
						${fmGoods.unit}							
					</td>							
				</tr>		
				<tr>	
					<th><%=TfmGoods.ALIAS_MIN_BATCH%></th>	
					<td>
						${fmGoods.minBatch}							
					</td>							
					<th><%=TfmGoods.ALIAS_STATUS%></th>	
					<td>
						${fmGoods.status}							
					</td>							
				</tr>		
				<tr>	
					<th><%=TfmGoods.ALIAS_BORN_AREA%></th>	
					<td>
						${fmGoods.bornArea}							
					</td>							
					<th><%=TfmGoods.ALIAS_STORAGE%></th>	
					<td>
						${fmGoods.storage}							
					</td>							
				</tr>		
				<tr>	
					<th><%=TfmGoods.ALIAS_OFFLINE_TIME%></th>	
					<td>
						${fmGoods.offlineTime}							
					</td>							
					<th><%=TfmGoods.ALIAS_CONTACTOR%></th>	
					<td>
						${fmGoods.contactor}							
					</td>							
				</tr>		
				<tr>	
					<th><%=TfmGoods.ALIAS_CONTACTOR_MOBILE%></th>	
					<td>
						${fmGoods.contactorMobile}							
					</td>							
					<th><%=TfmGoods.ALIAS_GOAL_AREA%></th>	
					<td>
						${fmGoods.goalArea}							
					</td>							
				</tr>		
				<tr>	
					<th><%=TfmGoods.ALIAS_PRE_ONLINE_TIME%></th>	
					<td>
						${fmGoods.preOnlineTime}							
					</td>							
					<th><%=TfmGoods.ALIAS_TRANSACTION_AREA%></th>	
					<td>
						${fmGoods.transactionArea}							
					</td>							
				</tr>		
				<tr>	
					<th><%=TfmGoods.ALIAS_SEND_TIME%></th>	
					<td>
						${fmGoods.sendTime}							
					</td>							
					<th><%=TfmGoods.ALIAS_TRANSACTION_TIME%></th>	
					<td>
						${fmGoods.transactionTime}							
					</td>							
				</tr>		
				<tr>	
					<th><%=TfmGoods.ALIAS_CAR_NO%></th>	
					<td>
						${fmGoods.carNo}							
					</td>							
					<th><%=TfmGoods.ALIAS_IMAGES%></th>	
					<td>
						${fmGoods.images}							
					</td>							
				</tr>		
				<tr>	
					<th><%=TfmGoods.ALIAS_DESCRIPTION%></th>	
					<td>
						${fmGoods.description}							
					</td>							
					<th><%=TfmGoods.ALIAS_DIAMETER%></th>	
					<td>
						${fmGoods.diameter}							
					</td>							
				</tr>		
				<tr>	
					<th><%=TfmGoods.ALIAS_DIAMETER_UNIT%></th>	
					<td>
						${fmGoods.diameterUnit}							
					</td>							
					<th><%=TfmGoods.ALIAS_COLOR%></th>	
					<td>
						${fmGoods.color}							
					</td>							
				</tr>		
				<tr>	
					<th><%=TfmGoods.ALIAS_IS_PACK%></th>	
					<td>
						${fmGoods.isPack}							
					</td>							
					<th><%=TfmGoods.ALIAS_PACK%></th>	
					<td>
						${fmGoods.pack}							
					</td>							
				</tr>		
				<tr>	
					<th><%=TfmGoods.ALIAS_FORMAT_DESC%></th>	
					<td>
						${fmGoods.formatDesc}							
					</td>							
					<th><%=TfmGoods.ALIAS_ONLINE_STATUS%></th>	
					<td>
						${fmGoods.onlineStatus}							
					</td>							
				</tr>		
				<tr>	
					<th><%=TfmGoods.ALIAS_USER_ID%></th>	
					<td>
						${fmGoods.userId}							
					</td>							
					<th><%=TfmGoods.ALIAS_PARENT_ID%></th>	
					<td>
						${fmGoods.parentId}							
					</td>							
				</tr>		
				<tr>	
					<th><%=TfmGoods.ALIAS_ACCESS_NUM%></th>	
					<td>
						${fmGoods.accessNum}							
					</td>							
					<th><%=TfmGoods.ALIAS_SOURCE%></th>	
					<td>
						${fmGoods.source}							
					</td>							
				</tr>		
				<tr>	
					<th><%=TfmGoods.ALIAS_OUTER_ID%></th>	
					<td>
						${fmGoods.outerId}							
					</td>							
					<th><%=TfmGoods.ALIAS_OUTER_NUMBER%></th>	
					<td>
						${fmGoods.outerNumber}							
					</td>							
				</tr>		
				<tr>	
					<th><%=TfmGoods.ALIAS_GRADE%></th>	
					<td>
						${fmGoods.grade}							
					</td>							
				</tr>		
		</table>
	</div>
</div>